/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as ScoringRouteImport } from './routes/scoring'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as JoinRouteImport } from './routes/join'
import { Route as GamesMasterRouteImport } from './routes/games-master'
import { Route as GamesRouteImport } from './routes/games'
import { Route as FlowDemoRouteImport } from './routes/flow-demo'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as SessionsNewRouteImport } from './routes/sessions/new'
import { Route as SessionsIdRouteImport } from './routes/sessions/$id'
import { Route as GamesNewRouteImport } from './routes/games/new'
import { Route as GamesIdRouteImport } from './routes/games/$id'

const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoringRoute = ScoringRouteImport.update({
  id: '/scoring',
  path: '/scoring',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesMasterRoute = GamesMasterRouteImport.update({
  id: '/games-master',
  path: '/games-master',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowDemoRoute = FlowDemoRouteImport.update({
  id: '/flow-demo',
  path: '/flow-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionsRoute,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GamesRoute,
} as any)
const SessionsNewRoute = SessionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SessionsRoute,
} as any)
const SessionsIdRoute = SessionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SessionsRoute,
} as any)
const GamesNewRoute = GamesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => GamesRoute,
} as any)
const GamesIdRoute = GamesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GamesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/flow-demo': typeof FlowDemoRoute
  '/games': typeof GamesRouteWithChildren
  '/games-master': typeof GamesMasterRoute
  '/join': typeof JoinRoute
  '/players': typeof PlayersRoute
  '/scoring': typeof ScoringRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/teams': typeof TeamsRoute
  '/games/$id': typeof GamesIdRoute
  '/games/new': typeof GamesNewRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/sessions/new': typeof SessionsNewRoute
  '/games/': typeof GamesIndexRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/flow-demo': typeof FlowDemoRoute
  '/games-master': typeof GamesMasterRoute
  '/join': typeof JoinRoute
  '/players': typeof PlayersRoute
  '/scoring': typeof ScoringRoute
  '/teams': typeof TeamsRoute
  '/games/$id': typeof GamesIdRoute
  '/games/new': typeof GamesNewRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/sessions/new': typeof SessionsNewRoute
  '/games': typeof GamesIndexRoute
  '/sessions': typeof SessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/flow-demo': typeof FlowDemoRoute
  '/games': typeof GamesRouteWithChildren
  '/games-master': typeof GamesMasterRoute
  '/join': typeof JoinRoute
  '/players': typeof PlayersRoute
  '/scoring': typeof ScoringRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/teams': typeof TeamsRoute
  '/games/$id': typeof GamesIdRoute
  '/games/new': typeof GamesNewRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/sessions/new': typeof SessionsNewRoute
  '/games/': typeof GamesIndexRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/flow-demo'
    | '/games'
    | '/games-master'
    | '/join'
    | '/players'
    | '/scoring'
    | '/sessions'
    | '/teams'
    | '/games/$id'
    | '/games/new'
    | '/sessions/$id'
    | '/sessions/new'
    | '/games/'
    | '/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/flow-demo'
    | '/games-master'
    | '/join'
    | '/players'
    | '/scoring'
    | '/teams'
    | '/games/$id'
    | '/games/new'
    | '/sessions/$id'
    | '/sessions/new'
    | '/games'
    | '/sessions'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/flow-demo'
    | '/games'
    | '/games-master'
    | '/join'
    | '/players'
    | '/scoring'
    | '/sessions'
    | '/teams'
    | '/games/$id'
    | '/games/new'
    | '/sessions/$id'
    | '/sessions/new'
    | '/games/'
    | '/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  FlowDemoRoute: typeof FlowDemoRoute
  GamesRoute: typeof GamesRouteWithChildren
  GamesMasterRoute: typeof GamesMasterRoute
  JoinRoute: typeof JoinRoute
  PlayersRoute: typeof PlayersRoute
  ScoringRoute: typeof ScoringRoute
  SessionsRoute: typeof SessionsRouteWithChildren
  TeamsRoute: typeof TeamsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scoring': {
      id: '/scoring'
      path: '/scoring'
      fullPath: '/scoring'
      preLoaderRoute: typeof ScoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games-master': {
      id: '/games-master'
      path: '/games-master'
      fullPath: '/games-master'
      preLoaderRoute: typeof GamesMasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow-demo': {
      id: '/flow-demo'
      path: '/flow-demo'
      fullPath: '/flow-demo'
      preLoaderRoute: typeof FlowDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/games/': {
      id: '/games/'
      path: '/'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof GamesRoute
    }
    '/sessions/new': {
      id: '/sessions/new'
      path: '/new'
      fullPath: '/sessions/new'
      preLoaderRoute: typeof SessionsNewRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/sessions/$id': {
      id: '/sessions/$id'
      path: '/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof SessionsIdRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/games/new': {
      id: '/games/new'
      path: '/new'
      fullPath: '/games/new'
      preLoaderRoute: typeof GamesNewRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/$id': {
      id: '/games/$id'
      path: '/$id'
      fullPath: '/games/$id'
      preLoaderRoute: typeof GamesIdRouteImport
      parentRoute: typeof GamesRoute
    }
  }
}

interface GamesRouteChildren {
  GamesIdRoute: typeof GamesIdRoute
  GamesNewRoute: typeof GamesNewRoute
  GamesIndexRoute: typeof GamesIndexRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesIdRoute: GamesIdRoute,
  GamesNewRoute: GamesNewRoute,
  GamesIndexRoute: GamesIndexRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

interface SessionsRouteChildren {
  SessionsIdRoute: typeof SessionsIdRoute
  SessionsNewRoute: typeof SessionsNewRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
}

const SessionsRouteChildren: SessionsRouteChildren = {
  SessionsIdRoute: SessionsIdRoute,
  SessionsNewRoute: SessionsNewRoute,
  SessionsIndexRoute: SessionsIndexRoute,
}

const SessionsRouteWithChildren = SessionsRoute._addFileChildren(
  SessionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  FlowDemoRoute: FlowDemoRoute,
  GamesRoute: GamesRouteWithChildren,
  GamesMasterRoute: GamesMasterRoute,
  JoinRoute: JoinRoute,
  PlayersRoute: PlayersRoute,
  ScoringRoute: ScoringRoute,
  SessionsRoute: SessionsRouteWithChildren,
  TeamsRoute: TeamsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
