/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as ScoringRouteImport } from './routes/scoring'
import { Route as RejoinRouteImport } from './routes/rejoin'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as JoinRouteImport } from './routes/join'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GamesRouteImport } from './routes/games'
import { Route as FlowDemoRouteImport } from './routes/flow-demo'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as SessionsNewRouteImport } from './routes/sessions/new'
import { Route as SessionsIdRouteImport } from './routes/sessions/$id'
import { Route as RsvpTokenRouteImport } from './routes/rsvp.$token'
import { Route as JoinJoinCodeRouteImport } from './routes/join_.$joinCode'
import { Route as JoinCodeRouteImport } from './routes/join/$code'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as GamesNewRouteImport } from './routes/games/new'
import { Route as GamesIdRouteImport } from './routes/games/$id'
import { Route as SessionsIdTvRouteImport } from './routes/sessions/$id_.tv'
import { Route as SessionsIdGameRouteImport } from './routes/sessions/$id_.game'

const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoringRoute = ScoringRouteImport.update({
  id: '/scoring',
  path: '/scoring',
  getParentRoute: () => rootRouteImport,
} as any)
const RejoinRoute = RejoinRouteImport.update({
  id: '/rejoin',
  path: '/rejoin',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowDemoRoute = FlowDemoRouteImport.update({
  id: '/flow-demo',
  path: '/flow-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionsRoute,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GamesRoute,
} as any)
const SessionsNewRoute = SessionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SessionsRoute,
} as any)
const SessionsIdRoute = SessionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SessionsRoute,
} as any)
const RsvpTokenRoute = RsvpTokenRouteImport.update({
  id: '/rsvp/$token',
  path: '/rsvp/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinJoinCodeRoute = JoinJoinCodeRouteImport.update({
  id: '/join_/$joinCode',
  path: '/join/$joinCode',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => JoinRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesNewRoute = GamesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => GamesRoute,
} as any)
const GamesIdRoute = GamesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GamesRoute,
} as any)
const SessionsIdTvRoute = SessionsIdTvRouteImport.update({
  id: '/$id_/tv',
  path: '/$id/tv',
  getParentRoute: () => SessionsRoute,
} as any)
const SessionsIdGameRoute = SessionsIdGameRouteImport.update({
  id: '/$id_/game',
  path: '/$id/game',
  getParentRoute: () => SessionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/flow-demo': typeof FlowDemoRoute
  '/games': typeof GamesRouteWithChildren
  '/history': typeof HistoryRoute
  '/join': typeof JoinRouteWithChildren
  '/players': typeof PlayersRoute
  '/rejoin': typeof RejoinRoute
  '/scoring': typeof ScoringRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/teams': typeof TeamsRoute
  '/games/$id': typeof GamesIdRoute
  '/games/new': typeof GamesNewRoute
  '/invite/$token': typeof InviteTokenRoute
  '/join/$code': typeof JoinCodeRoute
  '/join/$joinCode': typeof JoinJoinCodeRoute
  '/rsvp/$token': typeof RsvpTokenRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/sessions/new': typeof SessionsNewRoute
  '/games/': typeof GamesIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/sessions/$id/game': typeof SessionsIdGameRoute
  '/sessions/$id/tv': typeof SessionsIdTvRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/flow-demo': typeof FlowDemoRoute
  '/history': typeof HistoryRoute
  '/join': typeof JoinRouteWithChildren
  '/players': typeof PlayersRoute
  '/rejoin': typeof RejoinRoute
  '/scoring': typeof ScoringRoute
  '/settings': typeof SettingsRoute
  '/teams': typeof TeamsRoute
  '/games/$id': typeof GamesIdRoute
  '/games/new': typeof GamesNewRoute
  '/invite/$token': typeof InviteTokenRoute
  '/join/$code': typeof JoinCodeRoute
  '/join/$joinCode': typeof JoinJoinCodeRoute
  '/rsvp/$token': typeof RsvpTokenRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/sessions/new': typeof SessionsNewRoute
  '/games': typeof GamesIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/sessions/$id/game': typeof SessionsIdGameRoute
  '/sessions/$id/tv': typeof SessionsIdTvRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/flow-demo': typeof FlowDemoRoute
  '/games': typeof GamesRouteWithChildren
  '/history': typeof HistoryRoute
  '/join': typeof JoinRouteWithChildren
  '/players': typeof PlayersRoute
  '/rejoin': typeof RejoinRoute
  '/scoring': typeof ScoringRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/teams': typeof TeamsRoute
  '/games/$id': typeof GamesIdRoute
  '/games/new': typeof GamesNewRoute
  '/invite/$token': typeof InviteTokenRoute
  '/join/$code': typeof JoinCodeRoute
  '/join_/$joinCode': typeof JoinJoinCodeRoute
  '/rsvp/$token': typeof RsvpTokenRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/sessions/new': typeof SessionsNewRoute
  '/games/': typeof GamesIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/sessions/$id_/game': typeof SessionsIdGameRoute
  '/sessions/$id_/tv': typeof SessionsIdTvRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/flow-demo'
    | '/games'
    | '/history'
    | '/join'
    | '/players'
    | '/rejoin'
    | '/scoring'
    | '/sessions'
    | '/settings'
    | '/teams'
    | '/games/$id'
    | '/games/new'
    | '/invite/$token'
    | '/join/$code'
    | '/join/$joinCode'
    | '/rsvp/$token'
    | '/sessions/$id'
    | '/sessions/new'
    | '/games/'
    | '/sessions/'
    | '/sessions/$id/game'
    | '/sessions/$id/tv'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/flow-demo'
    | '/history'
    | '/join'
    | '/players'
    | '/rejoin'
    | '/scoring'
    | '/settings'
    | '/teams'
    | '/games/$id'
    | '/games/new'
    | '/invite/$token'
    | '/join/$code'
    | '/join/$joinCode'
    | '/rsvp/$token'
    | '/sessions/$id'
    | '/sessions/new'
    | '/games'
    | '/sessions'
    | '/sessions/$id/game'
    | '/sessions/$id/tv'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/flow-demo'
    | '/games'
    | '/history'
    | '/join'
    | '/players'
    | '/rejoin'
    | '/scoring'
    | '/sessions'
    | '/settings'
    | '/teams'
    | '/games/$id'
    | '/games/new'
    | '/invite/$token'
    | '/join/$code'
    | '/join_/$joinCode'
    | '/rsvp/$token'
    | '/sessions/$id'
    | '/sessions/new'
    | '/games/'
    | '/sessions/'
    | '/sessions/$id_/game'
    | '/sessions/$id_/tv'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  FlowDemoRoute: typeof FlowDemoRoute
  GamesRoute: typeof GamesRouteWithChildren
  HistoryRoute: typeof HistoryRoute
  JoinRoute: typeof JoinRouteWithChildren
  PlayersRoute: typeof PlayersRoute
  RejoinRoute: typeof RejoinRoute
  ScoringRoute: typeof ScoringRoute
  SessionsRoute: typeof SessionsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  TeamsRoute: typeof TeamsRoute
  InviteTokenRoute: typeof InviteTokenRoute
  JoinJoinCodeRoute: typeof JoinJoinCodeRoute
  RsvpTokenRoute: typeof RsvpTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scoring': {
      id: '/scoring'
      path: '/scoring'
      fullPath: '/scoring'
      preLoaderRoute: typeof ScoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rejoin': {
      id: '/rejoin'
      path: '/rejoin'
      fullPath: '/rejoin'
      preLoaderRoute: typeof RejoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow-demo': {
      id: '/flow-demo'
      path: '/flow-demo'
      fullPath: '/flow-demo'
      preLoaderRoute: typeof FlowDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/games/': {
      id: '/games/'
      path: '/'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof GamesRoute
    }
    '/sessions/new': {
      id: '/sessions/new'
      path: '/new'
      fullPath: '/sessions/new'
      preLoaderRoute: typeof SessionsNewRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/sessions/$id': {
      id: '/sessions/$id'
      path: '/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof SessionsIdRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/rsvp/$token': {
      id: '/rsvp/$token'
      path: '/rsvp/$token'
      fullPath: '/rsvp/$token'
      preLoaderRoute: typeof RsvpTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join_/$joinCode': {
      id: '/join_/$joinCode'
      path: '/join/$joinCode'
      fullPath: '/join/$joinCode'
      preLoaderRoute: typeof JoinJoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof JoinRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/new': {
      id: '/games/new'
      path: '/new'
      fullPath: '/games/new'
      preLoaderRoute: typeof GamesNewRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/$id': {
      id: '/games/$id'
      path: '/$id'
      fullPath: '/games/$id'
      preLoaderRoute: typeof GamesIdRouteImport
      parentRoute: typeof GamesRoute
    }
    '/sessions/$id_/tv': {
      id: '/sessions/$id_/tv'
      path: '/$id/tv'
      fullPath: '/sessions/$id/tv'
      preLoaderRoute: typeof SessionsIdTvRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/sessions/$id_/game': {
      id: '/sessions/$id_/game'
      path: '/$id/game'
      fullPath: '/sessions/$id/game'
      preLoaderRoute: typeof SessionsIdGameRouteImport
      parentRoute: typeof SessionsRoute
    }
  }
}

interface GamesRouteChildren {
  GamesIdRoute: typeof GamesIdRoute
  GamesNewRoute: typeof GamesNewRoute
  GamesIndexRoute: typeof GamesIndexRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesIdRoute: GamesIdRoute,
  GamesNewRoute: GamesNewRoute,
  GamesIndexRoute: GamesIndexRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

interface JoinRouteChildren {
  JoinCodeRoute: typeof JoinCodeRoute
}

const JoinRouteChildren: JoinRouteChildren = {
  JoinCodeRoute: JoinCodeRoute,
}

const JoinRouteWithChildren = JoinRoute._addFileChildren(JoinRouteChildren)

interface SessionsRouteChildren {
  SessionsIdRoute: typeof SessionsIdRoute
  SessionsNewRoute: typeof SessionsNewRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  SessionsIdGameRoute: typeof SessionsIdGameRoute
  SessionsIdTvRoute: typeof SessionsIdTvRoute
}

const SessionsRouteChildren: SessionsRouteChildren = {
  SessionsIdRoute: SessionsIdRoute,
  SessionsNewRoute: SessionsNewRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  SessionsIdGameRoute: SessionsIdGameRoute,
  SessionsIdTvRoute: SessionsIdTvRoute,
}

const SessionsRouteWithChildren = SessionsRoute._addFileChildren(
  SessionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  FlowDemoRoute: FlowDemoRoute,
  GamesRoute: GamesRouteWithChildren,
  HistoryRoute: HistoryRoute,
  JoinRoute: JoinRouteWithChildren,
  PlayersRoute: PlayersRoute,
  RejoinRoute: RejoinRoute,
  ScoringRoute: ScoringRoute,
  SessionsRoute: SessionsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  TeamsRoute: TeamsRoute,
  InviteTokenRoute: InviteTokenRoute,
  JoinJoinCodeRoute: JoinJoinCodeRoute,
  RsvpTokenRoute: RsvpTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
